Updated code to work for awslinux jenkins server so removed bat command

diff --git a/Jenkinsfile.ami_creation b/Jenkinsfile.ami_creation
--- a/Jenkinsfile.ami_creation
+++ b/Jenkinsfile.ami_creation
@@ -64,6 +64,13 @@ pipeline {
                 script {
                 if (isUnix()) {
                     sh """
+                    if ! command -v packer &> /dev/null; then
+                        echo "Packer not found. Downloading dynamically..."
+                        curl -fsSL https://releases.hashicorp.com/packer/1.10.2/packer_1.10.2_linux_amd64.zip -o packer.zip
+                        unzip -q -o packer.zip
+                        chmod +x packer
+                    fi
+                    export PATH="\$PWD:\$PATH"
                     packer init .
                     packer validate -var-file="dev.pkrvars.hcl" ${PACKER_TEMPLATE}
                     """
@@ -285,6 +292,7 @@ pipeline {
                     ]) {
                         if (isUnix()) {
                             sh """
+                            export PATH="\$PWD:\$PATH"
                             packer build \\
                                 -var "image_name=${params.IMAGE_NAME}" \\
                                 -var "region=${params.AWS_REGION}" \\
